[package]
name = "glua-sys"
version = "0.1.0"
authors = ["SpiralP <spiral.palmer@gmail.com>"]
edition = "2018"

[dependencies]

[build-dependencies]
bindgen = "0.54.1"

[target.'cfg(windows)'.build-dependencies]
cc = "1.0.58"

[features]
ci = []
